### ISSUE TITLE
Sorry, you can't activate this plugin unless the Beans framework is installed and a child theme is activated.

### ISSUE THREAD

**Issue by paaljoachim** [JeffCleverley/BeansSimpleShortcodes#1]
Hey Jeff

I am testing your plugin through Desktop Server (just updated and is using a higher version of PHP).
I am getting the "Sorry, you can't activate this plugin unless the Beans framework is installed and a child theme is activated." even though I have Beans and a child theme installed.

It might be another offline thing. 
Hmm I tested this on a live site as well. It is giving the same warning message.

So for now I am not able to use the plugin. I am looking forward to testing it out!

**Comment by JeffCleverley** [comment]
Thanks for catching this Paul.

I mistakenly replaced the child theme array with the text-domain... doh!
